base_url = "https://ogesandr.com"
title = "ogesandr"
author = "Oleksandr"
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
minify_html = true

theme = "apollo"
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/photos", url = "/photos", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/iorvd/", icon = "github" },
    { name = "rss", url = "/rss.xml", icon = "rss" },
]